version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: